<?php declare(strict_types=1);

/**
 * This file is part of the Nette Framework (https://nette.org)
 * Copyright (c) 2004 David Grudl (https://davidgrudl.com)
 */

namespace Nette\DI;

use Nette\DI\Definitions\Definition;
use function array_filter, array_map, array_merge, array_values, class_exists, class_implements, class_parents, count, implode, interface_exists, is_a, is_array, natsort, preg_match, sprintf;


/**
 * Resolves service names by type for autowiring.
 */
class Autowiring
{
	/** @var array<class-string, list<string>>  type => service names */
	private array $highPriority = [];

	/** @var array<class-string, list<string>>  type => service names */
	private array $lowPriority = [];

	/** @var array<class-string, class-string> */
	private array $excludedClasses = [];


	public function __construct(
		private readonly ContainerBuilder $builder,
	) {
	}


	/**
	 * Resolves a service name by (type, tag). When $tag is null, untagged services
	 * (i.e. those whose identity tag is the implicit "default") are preferred to break
	 * ambiguity. When $tag is non-null, only services with a matching identity tag are
	 * considered.
	 *
	 * @param class-string  $type
	 * @return ($throw is true ? string : ?string)
	 * @throws MissingServiceException when not found
	 * @throws ServiceCreationException when multiple match
	 */
	public function getByType(string $type, bool $throw = false, ?string $tag = null): ?string
	{
		$type = Helpers::normalizeClass($type);
		$candidates = $this->highPriority[$type] ?? [];

		if ($candidates === []) {
			if ($throw) {
				if (!class_exists($type) && !interface_exists($type)) {
					throw new MissingServiceException(sprintf("Service of type '%s' not found. Check the class name because it cannot be found.", $type));
				}

				foreach ($this->builder->getDefinitions() as $def) {
					if ($def->isTransient() && $def->getType() !== null && is_a($def->getType(), $type, allow_string: true)) {
						throw new ServiceCreationException(sprintf(
							'Service of type %s is transient and cannot be autowired into a shared service — inject a factory or use Container::create().',
							$type,
						));
					}
				}

				throw new MissingServiceException(sprintf('Service of type %s not found. Did you add it to configuration file?', $type));
			}

			return null;
		}

		$definitions = $this->builder->getDefinitions();

		if ($tag !== null) {
			$candidates = array_values(array_filter($candidates, static fn(string $name): bool => $definitions[$name]->getTag() === $tag));
			if ($candidates === []) {
				if ($throw) {
					throw new MissingServiceException(sprintf("Service of type %s with tag '%s' not found.", $type, $tag));
				}

				return null;
			}
		}

		if (count($candidates) === 1) {
			return $candidates[0];
		}

		// $tag === null and multiple candidates — try to disambiguate by preferring "default"-tagged services
		if ($tag === null) {
			$defaults = array_values(array_filter($candidates, static fn(string $name): bool => $definitions[$name]->getTag() === Definition::DefaultTag));
			if (count($defaults) === 1) {
				return $defaults[0];
			}
		}

		natsort($candidates);
		$names = array_values($candidates);
		throw new ServiceCreationException(sprintf(
			'Multiple services of type %s%s found: %s. %s',
			$type,
			$tag !== null ? sprintf(" with tag '%s'", $tag) : '',
			implode(', ', $this->describeServices($names, $tag === null)),
			'To replace one, decorate the existing service; to keep both, give one an identity tag.',
		));
	}


	/**
	 * Renders service names for an error message. An autogenerated name (e.g. "0142") is
	 * replaced by its concrete class — far more recognisable; a given name is kept as-is.
	 * When the lookup carried no tag, a non-default identity tag is appended as #tag so
	 * differently-tagged candidates are told apart (with a tagged lookup the tag is already
	 * stated once in the message). Identical labels fall back to appending the name.
	 *
	 * @param  list<string>  $names
	 * @return list<string>
	 */
	private function describeServices(array $names, bool $appendTag): array
	{
		$definitions = $this->builder->getDefinitions();
		$labels = $seen = [];
		foreach ($names as $name) {
			$def = $definitions[$name] ?? null;
			$type = $def?->getType();
			$base = $type !== null && preg_match('#^0\d+$#D', $name) ? $type : $name;
			$tag = $def?->getTag() ?? Definition::DefaultTag;
			$labels[$name] = $appendTag && $tag !== Definition::DefaultTag ? $base . '#' . $tag : $base;
			$seen[$labels[$name]] = ($seen[$labels[$name]] ?? 0) + 1;
		}

		return array_map(
			static fn(string $name): string => $seen[$labels[$name]] > 1 ? $labels[$name] . " ($name)" : $labels[$name],
			$names,
		);
	}


	/**
	 * Gets the service names and definitions of the specified type.
	 * @param class-string  $type
	 * @return array<string, Definitions\Definition>  service name => definition
	 */
	public function findByType(string $type): array
	{
		$type = Helpers::normalizeClass($type);
		$definitions = $this->builder->getDefinitions();
		$names = array_merge($this->highPriority[$type] ?? [], $this->lowPriority[$type] ?? []);
		$res = [];
		foreach ($names as $name) {
			$res[$name] = $definitions[$name];
		}

		return $res;
	}


	/**
	 * Excludes classes and their ancestors from autowiring lookup.
	 * @param array<class-string>  $types
	 */
	public function addExcludedClasses(array $types): void
	{
		foreach ($types as $type) {
			if (class_exists($type) || interface_exists($type)) {
				$type = Helpers::normalizeClass($type);
				$this->excludedClasses += class_parents($type) + class_implements($type) + [$type => $type];
			}
		}
	}


	/**
	 * Returns low-priority and high-priority type-to-service-names maps.
	 * @return array{array<class-string, list<string>>, array<class-string, list<string>>}
	 */
	public function getClassList(): array
	{
		return [$this->lowPriority, $this->highPriority];
	}


	/**
	 * Rebuilds the type-to-service-names index from current definitions.
	 */
	public function rebuild(): void
	{
		$this->lowPriority = $this->highPriority = $preferred = [];

		foreach ($this->builder->getDefinitions() as $name => $def) {
			if (!($type = $def->getType())) {
				continue;
			}

			$autowired = $def->getAutowired();
			if (is_array($autowired)) {
				foreach ($autowired as $k => $autowiredType) {
					if ($autowiredType === ContainerBuilder::ThisService) {
						$autowired[$k] = $type;
					} elseif (!is_a($type, $autowiredType, allow_string: true)) {
						throw new ServiceCreationException(sprintf(
							"Incompatible class %s in autowiring definition of service '%s'.",
							$autowiredType,
							$name,
						));
					}
				}
			}

			foreach (class_parents($type) + class_implements($type) + [$type] as $parent) {
				if (!$autowired || isset($this->excludedClasses[$parent])) {
					continue;
				} elseif (is_array($autowired)) {
					$priority = false;
					foreach ($autowired as $autowiredType) {
						if (is_a($parent, $autowiredType, allow_string: true)) {
							if (empty($preferred[$parent]) && isset($this->highPriority[$parent])) {
								$this->lowPriority[$parent] = array_merge($this->lowPriority[$parent] ?? [], $this->highPriority[$parent]);
								$this->highPriority[$parent] = [];
							}

							$preferred[$parent] = $priority = true;
							break;
						}
					}

					if (!$priority) {
						continue; // restrict: not autowired for a type outside its declared set — excluded, not a low-priority fallback (so it never leaks into a collection or tagged map for that type)
					}
				} else {
					$priority = empty($preferred[$parent]);
				}

				$list = $priority ? 'highPriority' : 'lowPriority';
				$this->$list[$parent][] = $name;
			}
		}
	}
}
