<?php declare(strict_types=1);

/**
 * Test: Nette\DI\ContainerBuilder.
 */

use Nette\DI;
use Tester\Assert;


require __DIR__ . '/../bootstrap.php';


$builder = new DI\ContainerBuilder;
$builder->addDefinition('one')
	->setType(stdClass::class)
	->addSetup('::1234');

Assert::exception(
	fn() => $builder->complete(),
	Nette\InvalidStateException::class,
	"Service 'one' (type of stdClass): Expected function, method or property name, '1234' given.",
);



$builder = new DI\ContainerBuilder;
$builder->addDefinition('extension.one')
	->setType(stdClass::class);
$builder->addDefinition('25_service')
	->setType(stdClass::class);

Assert::exception(
	fn() => $builder->getByType(stdClass::class),
	Nette\DI\ServiceCreationException::class,
	'Multiple services of type stdClass found: 25_service, extension.one. To replace one, decorate the existing service; to keep both, give one an identity tag.',
);



$builder = new DI\ContainerBuilder;
$builder->addDefinition('one')
	->setType(stdClass::class)
	->addSetup('$prop[]');

Assert::exception(
	fn() => $builder->complete(),
	Nette\InvalidStateException::class,
	"Service 'one' (type of stdClass): Missing argument for \$prop[].",
);



interface IShape
{
}

class CircleShape implements IShape
{
}

class SquareShape implements IShape
{
}

// autogenerated service names (e.g. "01") render as their concrete class — far clearer
$builder = new DI\ContainerBuilder;
$builder->addDefinition(null)->setType(CircleShape::class);
$builder->addDefinition(null)->setType(SquareShape::class);

Assert::exception(
	fn() => $builder->getByType(IShape::class),
	Nette\DI\ServiceCreationException::class,
	'Multiple services of type IShape found: CircleShape, SquareShape. To replace one, decorate the existing service; to keep both, give one an identity tag.',
);


// with no lookup tag, differing identity tags are shown as #tag to tell candidates apart
$builder = new DI\ContainerBuilder;
$builder->addDefinition(null)->setType(CircleShape::class)->setTag('a');
$builder->addDefinition(null)->setType(SquareShape::class)->setTag('b');

Assert::exception(
	fn() => $builder->getByType(IShape::class),
	Nette\DI\ServiceCreationException::class,
	'Multiple services of type IShape found: CircleShape#a, SquareShape#b. To replace one, decorate the existing service; to keep both, give one an identity tag.',
);
